CREATE TABLE IF NOT EXISTS users(
	id SERIAL PRIMARY KEY,
	email VARCHAR(50) NOT NULL,
	password VARCHAR(30) NOT NULL,
	user_information_id INTEGER REFERENCES user_informations (id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
